Repository assimp/assimp, pull requests merged in 2024-11, with the labels that each got.

#5879 Material: Fix the build for c compiler
  include/assimp/material.h
Labels: Build, API

#5894 Obj: fix nullptr access.
  code/AssetLib/Obj/ObjFileImporter.cpp
Labels: Bug

#5892 Add CI to automatically build and attach binaries to releases
  .github/workflows/cd.yml
Labels: Quality
