Repository assimp/assimp, pull requests merged in 2025-05, with the labels that each got.

#6122 fix: possible Heap-based Buffer Overflow in ConvertToUTF8 function
  code/Common/BaseImporter.cpp
Labels: Char encoding

#6121 support for cmake findpackage module mode
  cmake-modules/Findassimp.cmake
Labels: Build

#6116 add missing constants
  port/PyAssimp/pyassimp/postprocess.py
Labels: Postprocessing

#6150 Fix out-of-bounds dereferencing
  code/AssetLib/FBX/FBXExporter.cpp
Labels: Fuzzer, Security Risk

#6000 [#5983] Fix bugs introduced in fbx export
  code/AssetLib/FBX/FBXExporter.cpp
Labels: FBX, Export, Regression

#6187 Doc: add C++ / c minimum
  Build.md
Labels: Doc

#6186 Fix issue compiling when assimp added as subdirectory
  CMakeLists.txt
Labels: Build, Char encoding

#6143 Add explicit "fallthrough" to switch
  code/AssetLib/FBX/FBXExportProperty.cpp
Labels: Build

#6060 Fix a bug in importing binary PLY file (#1)
  include/assimp/IOStreamBuffer.h
  test/models/PLY/cube_binary_starts_with_nl.ply
  test/unit/utPLYImportExport.cpp
Labels: PLY

#6102 Fix export fbx PolygonVertexIndex
  code/AssetLib/FBX/FBXExporter.cpp
Labels: FBX, Export

#6154 fix: closes #6069 CVE-2025-3196
  code/AssetLib/MD2/MD2Loader.cpp
Labels: Security Risk, MD2
