Repository assimp/assimp, pull requests merged in 2025-07, with the labels that each got.

#5537 Add windows clang to CI
  .github/workflows/ccpp.yml
  CMakeLists.txt
  code/CMakeLists.txt
  contrib/zlib/gzguts.h
  contrib/zlib/gzlib.c
  contrib/zlib/gzread.c
  contrib/zlib/gzwrite.c
  contrib/zlib/zutil.c
  include/assimp/types.h
  test/CMakeLists.txt
  test/unit/TestIOStream.h
  test/unit/Tools/TestTools.h
  test/unit/UnitTestFileGenerator.h
  test/unit/utBlenderImportExport.cpp
  test/unit/utBlenderIntermediate.cpp
  test/unit/utDefaultIOStream.cpp
  test/unit/utIOStreamBuffer.cpp
  test/unit/utglTF2ImportExport.cpp
Labels: Build

#6273 Update Build.md
  Build.md
Labels: Build, Doc

#6252 AC: Support Double-Sided Faces
  code/AssetLib/AC/ACLoader.cpp
  test/models/AC/doubleSidedFace.ac
  test/unit/utACImportExport.cpp
Labels: AC
